### ISSUE TITLE
question about REC result 

### ISSUE THREAD

**Issue by FightingFighting** [shikras/shikra#13]
Hi,

Thank you for your great job.

could you explain the result of model “ofa” in the Table 3 in your paper ? i did not find the data in "ofa" paper.

best,
zhi

**Comment by zzhanghub** [comment]
Thank you for your interest in our work. kindly note that OFA has released their pretraining [ckpt](https://github.com/OFA-Sys/OFA/blob/main/checkpoints.md). By conducting tests on these specified datasets, you'll be able to obtain the outcomes.
