### ISSUE TITLE
provide a run script for running one conversion

### ISSUE THREAD

**Issue by wuwuwuxxx** [shikras/shikra#14]
Can u provide a run script for running one conversion based on one image and one text input?

**Comment by HXLYTT** [comment]
Same with me!!!!,So many questions to run eval.

**Comment by zzj403** [comment]
Yeah, also need. I also recommand a web server code like LLaVA [https://github.com/haotian-liu/LLaVA](url)

**Comment by kq-chen** [comment]
sorry for the inconvenience. the demo and [online demo](http://demo.zhaozhang.net:7860/) is updated now.
