### ISSUE TITLE
A question about the installed "transformers"

### ISSUE THREAD

**Issue by Lanxin1011** [shikras/shikra#19]
Thanks for the awesome work! I encountered a problem when installing the transformers when conducting `pip install -r requirement.txt`. The Error info is attached below.

Is it possible if I simply run `pip install transformers` to install this package? Or I must install the "transformers" provided by the "huggingface"? 

Looking forward to your reply.

> (shikra) zlx@ubuntu-Super-Server:~/shikra$ pip install git+https://github.com/huggingface/transformers@cae78c46
Collecting git+https://github.com/huggingface/transformers@cae78c46
  Cloning https://github.com/huggingface/transformers (to revision cae78c46) to /tmp/pip-req-build-vzu547ee
  Running command git clone --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-vzu547ee
  fatal: unable to access 'https://github.com/huggingface/transformers/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
  error: subprocess-exited-with-error
  
  × git clone --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-vzu547ee did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-vzu547ee did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by kq-chen** [comment]
i am not sure if this is a net connection error, we provide a zipfile at [this link](https://drive.google.com/file/d/16WH3993G1k4YeYIzT6XN5mev-mQa3OuW/view?usp=sharing).
