### ISSUE TITLE
How is the toy shikra trained in Table 2?

### ISSUE THREAD

**Issue by qumengxue** [shikras/shikra#20]
I find this project extremely interesting and I'm eager to follow its progress. I have a question regarding the training process mentioned in the paper. The paper refers to **_"toy shikra/toy model"_** many times. I'm curious to know how the toy shikra was trained, particularly the results mentioned in Table 2. Was it trained only with REC datasets and initialized from the llama model?

**Comment by kq-chen** [comment]
it is trained on a combination of three REC datasets and initialized from the **llava-7b** model

**Comment by qumengxue** [comment]
Got it, thanks for your reply!
