### ISSUE TITLE
infer  problem: ModuleNotFoundError: No module named 'petrel_client'

### ISSUE THREAD

**Issue by SeeeeShiwei** [shikras/shikra#22]
def init_ceph_client_if_needed():
    global client
    if client is None:
        logger.info(f"initializing ceph client ...")
        st = time.time()
        from petrel_client.client import Client  # noqa
        client = Client(enable_mc=True)
        ed = time.time()
        logger.info(f"initialize client cost {ed - st:.2f} s")

I met a problem 
"ModuleNotFoundError: No module named 'petrel_client"

How can I solve it? Thanks

**Comment by kq-chen** [comment]
a [similar issue](https://github.com/shikras/shikra/issues/12#issue-1789385842) has been asked before. You can find the solution for it [here](https://github.com/shikras/shikra/issues/12#issuecomment-1637412360).

> I apologize for any confusion caused earlier.
> 
> As mentioned by @MacavityT, the `petrel_client` module is an internal component of Sensetime that is utilized for loading images from a distributed storage system. When attempting to load a file from an S3 path like `balabala:s3://`, it triggers the initialization of `petrel_client`, resulting in the error you encountered. To work with a dataset, you need to modify the `image_folder` field in the configuration file.
>
> To illustrate, let's consider this pope testset as an example. You can update the `image_folder` field in the `config/_base_/dataset/DEFAULT_TEST_POPE_VARIANT.py` file as follows:
>
> Before modification:
> ```python
> POPE_TEST_COMMON_CFG = dict(
>     type='POPEVQADataset',
>    image_folder=r'openmmlab1424:s3://openmmlab/datasets/detection/coco/val2014',
> )
> ```
>
> After modification:
> ```python
> POPE_TEST_COMMON_CFG = dict(
>    type='POPEVQADataset',
>    image_folder=r'path/to/coco/val2014/on/your/computer',
>)
>```
>
>I hope this clarification helps. If you have any further questions or need additional assistance, please let me know.
