### ISSUE TITLE
what's the image preprocess method?

### ISSUE THREAD

**Issue by double-fire-0** [shikras/shikra#25]
It seems the image preprocess method are saved in the ckpt, and can't obtain from the code.

**Comment by kq-chen** [comment]
the image is first expanded to square by padding with white background. the related code can be found [here](https://github.com/shikras/shikra/blob/ff79a4ced85d21739e1a4c5cec9e1e8f896b962c/mllm/dataset/utils/transform.py#L91C1-L91C1).
then the expanded image is sent to the default clip image preprocessor.

**Comment by double-fire-0** [comment]
got it! thx
