### ISSUE TITLE
May I ask if it supports multi image input, that is, multiple images and one text

### ISSUE THREAD

**Issue by hangzeli08** [shikras/shikra#26]
请问支持多图输入吗，就是多个图像，一条文本这样

**Comment by chenkq7** [comment]
No, it currently does not support multi-image input.

**Comment by kq-chen** [comment]
no, it currently does not support multi-image input.

**Comment by hangzeli08** [comment]
> 不，目前不支持多图像输入。

Would you consider adding multi image functionality and training a version for release？

**Comment by hangzeli08** [comment]
> 不，目前不支持多图像输入。

Would it be better if I manually change the model architecture and average multiple images？

**Comment by hangzeli08** [comment]
如果我手动改变模型架构，多图求平均值，效果会好吗
