### ISSUE TITLE
gqa_scene_graph_index.json

### ISSUE THREAD

**Issue by Morizhaoyang** [shikras/shikra#28]
i wanna know where is  gqa_scene_graph_index.json

**Comment by kq-chen** [comment]
Please note that while the data ZIP file contains some gqa annotations, no gqa data was utilized during training. FYI, the gqa_scene_graph_index.json file has been updated to the latest ZIP file. You can re-download [the entire ZIP file](https://drive.google.com/file/d/1CNLu1zJKPtliQEYCZlZ8ykH00ppInnyN/view?usp=drive_link), or only download the gqa_scene_graph_index.json file from [a separate link](https://drive.google.com/file/d/1hdhe_LotuX_74O9UrZ1bYr5QRdZjSjCN/view?usp=drive_link).
