### ISSUE TITLE
question: How to get output for a single image

### ISSUE THREAD

**Issue by yuntaodu** [shikras/shikra#39]
Hi, thanks for your excellent work. I wonder to know how to get ouptut for a single image, as the inference code is used for a dataset. How could we use for a single image simply?

**Comment by hongkunhao** [comment]
> Hi, thanks for your excellent work. I wonder to know how to get ouptut for a single image, as the inference code is used for a dataset. How could we use for a single image simply?

Hello, do you have any solution? Could you share some experiences? Thanks! @yuntaodu
