### ISSUE TITLE
ValueError: Trying to set a tensor of shape torch.Size([32003, 4096]) in "weight" (which has shape torch.Size([32000, 4096])), this look incorrect.

### ISSUE THREAD

**Issue by qinbaigao** [shikras/shikra#57]
When I load "shikra-7b-delta-v1":  _delta = ShikraLlamaForCausalLM.from_pretrained(delta_path, torch_dtype=torch.float16, low_cpu_mem_usage=True)_,I have this issue: _ValueError: Trying to set a tensor of shape torch.Size([32003, 4096]) in "weight" (which has shape torch.Size([32000, 4096])), this look incorrect_.

**Comment by pange1802703882** [comment]
Sorry, How to solve this problem ?

**Comment by pange1802703882** [comment]
My error is " RuntimeError: The size of tensor a (32003) must match the size of tensor b (32016) "
