### ISSUE TITLE
which torch version used?

### ISSUE THREAD

**Issue by JiaweiZhao-git** [shikras/shikra#6]
the new version is 2.0.1, I wonder this project use 1.* or 2.*?

**Comment by kq-chen** [comment]
The torch and torchvision utilized in our environment are [torch-1.13.1+cu117](https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl) and [torchvision-0.14.1+cu117](https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bcu117-cp310-cp310-linux_x86_64.whl)
